server:
  port: 8080
  
spring:
  datasource:
    name: test
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      filter: stat
      #mysql驱动
      driver-class-name: com.mysql.cj.jdbc.Driver
      #基本属性
      url: jdbc:mysql://118.24.118.85:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=true
      username: root
      password: 123456
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: LEGACYHTML5
    cache: false
    
    #文件上传相关设置
  servlet:
    multipart:
      max-file-size: 10000000
      max-request-size: 10000000
      
  #devtools插件
  devtools:
    livereload:
      enabled: true #是否支持livereload
      port: 35729
    restart:
      enabled: true #是否支持热部署
      
  #spring-aop配置
  aop:
    auto: true #启用@Aspectj注解驱动的切面，允许Spring创建基于类的代理
    proxy-target-class: true
    
#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.SpringBootTest1.entity
  
#mybatis分页插件pagehelper设置
pagehelper:
  reasonable: true
  support-methods-arguments: true
